#-*- coding: utf-8 -*-
#!/usr/bin/python
#--------------------------------
##  @package pays
##  \brief Gestion des pays & drapeaux 
##  \author Bouilly Loïc & Kerhel Jélani
##  \version 1
##  \date 17 avril 2012
##  
## 

#--------------------------------

## Liste des pays par Nom leur numéros de la liste correspond au numéro de base
def pays(x) :
    liste_pays = [#Afrique
    "à l'Afrique du Sud",
    "à l'Algérie",
    "à l'Angola",
    "au Bénin",
    "au Botswana",
    "au Burkina Faso",
    "au Burundi",
    "au Cameroun",
    "au Cap-Vert",
    "à la République centrafricaine",
    "aux Comores",
    "à la République du Congo",
    "à la République démocratique du Congo",
    "à la Côte d'Ivoire",
    "au Djibouti",
    "à l'Égypte",
    "à l'Érythrée",
    "à l'Éthiopie",
    "au Gabon",
    "à la Gambie",
    "au Ghana",
    "à la Guinée",
    "au Guinée-Bissau",
    "à la Guinée équatoriale",
    "au Kenya",
    "au Lesotho",
    "au Liberia",
    "à la Libye",
    "à Madagascar",
    "au Malawi",
    "au Mali",
    "au Maroc",
    "à la Maurice",
    "à la Mauritanie",
    "au Mozambique",
    "à la Namibie",
    "au  Niger",
    "au Nigeria",
    "à l'Ouganda",
    "au Rwanda",
    "au Sahara Occidental",
    "à Sao Tomé-et-Principe",
    "au Sénégal",
    "aux Seychelles",
    "au Sierra Leone",
    "à la Somalie",
    "au Soudan",
    "au Soudan du Sud",
    "au Swaziland",
    "à la Tanzanie",
    "au Tchad",
    "au Togo",
    "à la Tunisie",
    "au Zambie",
    "au Zimbabwe",
    ## Amérique
    "à Antigua-et-Barbuda",
    "à l'Argentine",
    "aux Bahamas",
    "à la Barbade",
    "au Belize",
    "à la Bolivie",
    "au Brésil",
    "au Canada",
    "au Chili",
    "à la Colombie",
    "au Costa Rica",
    "à Cuba",
    "à la République dominicaine",
    "à la Dominique",
    "à l'Équateur",
    "aux États-Unis",
    "à la Grenade",
    "au Guatemala",
    "au Guyana",
    "à Haïti",
    "à l'Honduras",
    "à la Jamaïque",
    "au Mexique",
    "au Nicaragua",
    "au Panama",
    "au Paraguay",
    "au Pérou",
    "à Saint-Christophe-et-Niévès",
    "à Sainte-Lucie",
    "à Saint-Vincent-et-les-Grenadines",
    "au Salvador",
    "au Suriname",
    "à Trinité-et-Tobago",
    "à l'Uruguay",
    "au Venezuela",
    #  "Asie"
    "à l'Afghanistan",
    "à l'Arabie saoudite",
    "à l'Arménie",
    "à l'Azerbaïdjan",
    "au Bahreïn",
    "au Bangladesh",
    "au Bhoutan",
    "à la Birmanie",
    "à Brunei",
    "au Cambodge",
    "à la Chine",
    "à la Corée du Nord",
    "à la Corée du Sud",
    "aux Émirats arabes unis",
    "à la Géorgie",
    "à l'Inde",
    "à l'Indonésie",
    "à l'Irak",
    "à l'Iran",
    "à l'Israël",
    "au Japon",
    "à la Jordanie",
    "au Kazakhstan",
    "au Kirghizistan",
    "au Koweït",
    "au Laos",
    "au Liban",
    "à la Malaisie",
    "aux Maldives",
    "à la Mongolie",
    "au Népal",
    "à l'Oman",
    "à l'Ouzbékistan",
    "au Pakistan",
    "aux Philippines",
    "au Qatar",
    "à Singapour",
    "au Sri Lanka",
    "à la Syrie",
    "au Tadjikistan",
    "à la Thaïlande",
    "au Timor oriental",
    "au Turkménistan",
    "à la Turquie",
    "au Viêt Nam",
    "au Yémen",
    #  "Europe"
    "à l'Albanie",
    "à l'Allemagne",
    "à Andorre",
    "à l'Autriche",
    "à la Belgique",
    "à la Biélorussie",
    "à la Bosnie-Herzégovine",
    "à la Bulgarie",
    "au Chypre",
    "à la Croatie",
    "au Danemark",
    "à l'Espagne",
    "à l'Estonie",
    "à la Finlande",
    "à la France",
    "à la Grèce",
    "à la Hongrie",
    "à l'Irlande",
    "à l'Islande",
    "à l'Italie",
    "à la Lettonie",
    "au Liechtenstein",
    "à la Lituanie",
    "au Luxembourg",
    "à la Macédoine",
    "à Malte",
    "à la Moldavie",
    "à Monaco",
    "au Monténégro",
    "à la Norvège",
    "aux Pays-Bas",
    "à la Pologne",
    "au Portugal",
    "à la République tchèque",
    "à la Roumanie",
    "au  Royaume-Uni",
    "à la Russie",
    "à Saint-Marin",
    "à la Serbie",
    "à la Slovaquie",
    "à la Slovénie",
    "à la Suède",
    "à la Suisse",
    "à l'Ukraine",
    "au Vatican",
    ##  "Océanie"
    "à l'Australie",
    "aux Fidji",
    "au Kiribati",
    "aux îles Marshall",
    "à la Micronésie",
    "au Nauru",
    "à la Nouvelle-Zélande",
    "au Palaos",
    "à la Ppouasie-Nouvelle-Guinée",
    "au Salomon",
    "au Samoa",
    "au Tonga",
    "au Tuvalu",
    "au Vanuatu",
    ]
    pays2 = unicode(liste_pays[x],"utf-8")
    #print pays2
    #pays3 = u""+liste_pays[x]
    return pays2
################################################################
#               Liste des drapeaux par odres alphabetique      #
################################################################
def liste_drapeaux(x):
    """! \brief """
    find_drapeaux =["afrique_du_sud.png",
                    "algerie.png",
                    "angoli.png",
                    "benin.png",
                    "bostswana.png",
                    "burkina.png",
                    "burundi.png",
                    "cameroun.png",
                    "cap_vert.png",
                    "afrique_central.png",
                    "comoros.png",
                    "congo.png",
                    "rep_congo.png",
                    "cote_ivoire.png",
                    "djibouti.png",
                    "egypte.png",
                    "erythree.png",
                    "ethiopie.png",
                    "gabon.png",
                    "gambie.png",
                    "ghana.png",
                    "guine.png",
                    "guinea_bissau.png",
                    "equa_guine.png",
                    "kenya.png",
                    "lesotho.png",
                    "liberia.png",
                    "libye.png",
                    "madagascar.png",
                    "malawi.png",
                    "mali.png",
                    "maroc.png",
                    "maurice.png",
                    "mauritanie.png",
                    "mozambique.png",
                    "nanibie.png",
                    "niger.png",
                    "nigeria.png",
                    "uganda.png",
                    "rwanda.png",
                    "sahara_occidental.png",
                    "sao_tome.png",
                    "senegal.png",
                    "seychelles.png",
                    "sierra_leonne.png",
                    "somalie.png",
                    "sudan.png",
                    "sudan_sud.png",
                    "swaziland.png",
                    "tanzany.png",
                    "tchad.png",
                    "togo.png",
                    "tunisie.png",
                    "zambie.png",
                    "zimbabwe.png",
                    "antigua.png",
                    "argentine.png",
                    "bahamas.png",
                    "barbade.png",
                    "belize.png",
                    "bolivie.png",
                    "bresil.png",
                    "canada.png",
                    "chilie.png",
                    "colombie.png",
                    "costa_rica.png",
                    "cuba.png",
                    "dominicains.png",
                    "dominica.png",
                    "equateur.png",
                    "etat_unis.png",
                    "grenade.png",
                    "guatemala.png",
                    "guyanne.png",
                    "haiti.png",
                    "hondura.png",
                    "jamaique.png",
                    "mexique.png",
                    "nicaragua.png",
                    "panama.png",
                    "paraguay.png",
                    "perou.png",
                    "kitts_et_nevis.png",
                    "lucie.png",
                    "saint_vincent.png",
                    "salvador.png",
                    "suriname.png",
                    "trinidad.png",
                    "uruguay.png",
                    "venezuela.png",
                    "afghanistan.png",
                    "arabie_saoudit.png",
                    "armenie.png",
                    "azerbajan.png",
                    "bahrein.png",
                    "bangladesh.png",
                    "bhutan.png",
                    "birmanie.png",
                    "brunei.png",
                    "cambodge.png",
                    "chine.png",
                    "core_du_nord.png",
                    "core_sud.png",
                    "emirat_arabe_unis.png",
                    "georgie.png",
                    "inde.png",
                    "indonesie.png",
                    "irak.png",
                    "iran.png",
                    "israel.png",
                    "japon.png",
                    "jordanie.png",
                    "kazakhstan.png",
                    "kyrgyzstan.png",
                    "koweit.png",
                    "laos.png",
                    "liban.png",
                    "malaysie.png",
                    "maldives.png",
                    "mongolie.png",
                    "nepal.png",
                    "oman.png",
                    "uzbekistan.png",
                    "pakistan.png",
                    "philippine.png",
                    "qatar.png",
                    "singapour.png",
                    "sri_lanka.png",
                    "syrie.png",
                    "tajikistan.png",
                    "thailand.png",
                    "timor.png",
                    "turkmeistan.png",
                    "turquie.png",
                    "vietnam.png",
                    "yemen.png",
                    "albanie.png",
                    "allemagne.png",
                    "andore.png",        
                    "autriche.png",
                    "belgique.png",
                    "belarusse.png",
                    "bosnie.png",
                    "bulgarie.png",
                    "cyprus.png",
                    "croatie.png",
                    "dannemark.png",
                    "espagne.png",
                    "estonie.png",
                    "finland.png",
                    "france.png",
                    "grece.png",
                    "hongrie.png",
                    "ireland.png",
                    "island.png",
                    "italie.png",
                    "latvia.png",
                    "liechtenstien.png",
                    "lituanie.png",
                    "luxembourg.png",
                    "macedoine.png",
                    "malte.png",
                    "moldovie.png",
                    "monaco.png",
                    "montenegro.png",
                    "norvege.png",
                    "pays_bas.png",
                    "pologne.png",
                    "portugal.png",
                    "rep_tcheque.png",
                    "roumanie.png",
                    "angleterre.png",
                    "russie.png",
                    "saint_marin.png",
                    "serbie.png",
                    "slovaquie.png",
                    "slovenie.png",
                    "suede.png",
                    "suisse.png",
                    "ukraine.png",
                    "vatican.png",
                    "australie.png",
                    "fidji.png",
                    "kiribati.png",
                    "marshall_island.png",
                    "miconisia.png",
                    "nauru.png",
                    "zeland.png",
                    "palau.png",
                    "papouasie-new-gui.png",
                    "solomon_island.png",
                    "samoa.png",
                    "tonga.png",
                    "tuvalu.png",
                    "vanuatu.png",
        ]
    return find_drapeaux[x]




